name: Smoke

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      version: 0.1.${{ github.run_number }}

    steps:
    - uses: actions/checkout@v2

    - name: Environment variables
      run: |
        echo "Run ID = ${{ github.run_id }}"
        echo "Run Number = ${{ github.run_number }}"
        echo "Event Name = ${{ github.event_name }}"
        echo "Ref = ${{ github.ref }}"
        echo "Head Ref = ${{ github.head_ref }}"
        echo "Base Ref = ${{ github.base_ref }}"
        echo "Workspace = ${{ github.workspace }}"
        echo "Version = ${{ env.version }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet restore ./src/All/All.csproj

    - name: Build
      run: dotnet build --no-restore --configuration Debug --nologo -p:Version=${{ env.version }}

    - name: Test
      run: dotnet test --no-build --configuration Debug --nologo --collect:"XPlat code coverage"

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v1

    - name: Pack
      run: |
        dotnet pack --output ./artifacts --no-build --configuration Debug --nologo -p:PackageVersion=${{ env.version }}
        dotnet pack ./src/All/All.csproj --output ./artifacts --no-build --configuration Debug --nologo -p:PackageVersion=${{ env.version }}

    - name: Save
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts-${{ env.version }}
        path: |
          ./artifacts
          !**/*.snupkg
